apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: elector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elector
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elector
subjects:
  - kind: ServiceAccount
    name: elector
